FROM node:lts-alpine3.19

ENV NODE_ENV=production

WORKDIR /app-money

COPY package*.json ./

RUN npm install 

RUN mv node_modules /app-money
COPY . .

EXPOSE 880
RUN chown -R node /usr/src/app-money

USER node
CMD [ "npm", "start" ]